### ISSUE TITLE
[Bug]: Close button missaligned

### ISSUE THREAD

**Issue by Tylopilus** [bautistaaa/typehero#479]
### What happened?

![image](https://github.com/bautistaaa/typehero/assets/45148577/d048b1f7-f1c7-4c74-9151-a83cafb55f20)

**Comment by MahendraBishnoi29** [comment]
I'll take care of this one also @PickleNik

**Comment by vivekKumarSinghH** [comment]
I have debugged this issue. 
The issue arises because the close button is placed outside of the dialog title using CSS positioning at the top right corner!

As a solution, we can move the close button inside the dialog header or we can adjust the position of the close button using CSS position.
[image](https://github.com/bautistaaa/typehero/assets/72158561/b0154ac2-ab75-4ab0-8edd-52b8b44a3410)
Please assign this issue to me @PickleNik

**Comment by PickleNik** [comment]
no worries, this is not a very big issue. But yes in the future please look if somebody is already working on the issue, unless you've already had work done related to it previously (which I am assuming _might've_ happened here?)

Thanks to everyone for contributing!
